import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import {mkdtemp,rm} from 'node:fs/promises';
import {start} from '../tools/lab/agents-panel-server.mjs';
import {append} from '../tools/lab/agents-panel-fixture.mjs';
import {createApp} from '../server.mjs';

test('real lab HTTP waits for journal append, returns a delta, keeps pairing and rejects queries',async t=>{
  const parent=await mkdtemp(path.join(os.tmpdir(),'ponte-live-http-'));
  t.after(()=>rm(parent,{recursive:true,force:true}));
  const root=path.join(parent,'fixture');
  const lab=await start({root,port:0});
  t.after(()=>lab.app.close());
  const headers={Authorization:`Bearer ${lab.token}`};
  const route='/api/agents/p-5111-30000/transcript';
  assert.equal((await fetch(lab.base+route)).status,401);
  const first=await(await fetch(lab.base+route,{headers})).json();
  assert.match(first.cursor,/^[a-f0-9]{32}$/);
  assert.equal(first.reset,true);
  let settled=false;
  const before=Date.now();
  const held=fetch(`${lab.base}${route}?since=${first.cursor}&wait=10`,{headers}).then(async response=>{settled=true;assert.equal(response.status,200);return response.json();});
  await new Promise(resolve=>setTimeout(resolve,70));
  assert.equal(settled,false,'unchanged transcript holds the HTTP request');
  await append(root);
  const delta=await held;
  assert.equal(delta.reset,false);
  assert.notEqual(delta.cursor,first.cursor);
  assert.ok(delta.messages.length>0 && delta.messages.length<first.messages.length+2);
  assert.ok(Date.now()-before<5000,'append appears within watcher interval');
  const idle=await(await fetch(`${lab.base}${route}?since=${delta.cursor}&wait=0`,{headers})).json();
  assert.equal(idle.unchanged,true);
  assert.deepEqual(idle.messages,[]);
  assert.ok(JSON.stringify(idle).length<500);
  for(const query of ['?since=bad','?wait=-1','?wait=1&wait=2'])assert.equal((await fetch(lab.base+route+query,{headers})).status,400);
  const controller=new AbortController();
  const gone=fetch(`${lab.base}${route}?since=${delta.cursor}&wait=10`,{headers,signal:controller.signal}).catch(error=>error.name);
  controller.abort();
  assert.equal(await gone,'AbortError');
});

test('transcript HTTP preserves the global two-read budget while idle waits use no IO slot',async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'ponte-transcript-budget-'));
  t.after(()=>rm(root,{recursive:true,force:true}));
  const cursor='a'.repeat(32), pending=new Map();
  const agents={list:async()=>({items:[]}),transcript:async(id,{since})=>{
    if (!since) await new Promise(resolve=>pending.set(id,resolve));
    return {id,cursor,available:true,unchanged:since===cursor,messages:[]};
  }};
  const app=await createApp({rootDir:root,dataDir:path.join(root,'private'),token:'ponte_transcript_public_test_token_0000',agents,desktop:{action:async()=>({}),getState:async()=>({})},terminals:{list:async()=>({})},trustedHosts:[]});
  t.after(()=>app.close());
  await new Promise(resolve=>app.server.listen(0,'127.0.0.1',resolve));
  const base=`http://127.0.0.1:${app.server.address().port}/api/agents/`;
  const headers={Authorization:'Bearer ponte_transcript_public_test_token_0000'};
  const request=(id,query='',signal)=>fetch(`${base}${id}/transcript${query}`,{headers,signal});
  const first=request('p-1-2'), second=request('p-2-2');
  for(let n=0;n<100 && pending.size<2;n++)await new Promise(resolve=>setTimeout(resolve,5));
  assert.equal(pending.size,2);
  assert.equal((await request('p-3-2')).status,429);
  for(const resolve of pending.values())resolve();
  assert.equal((await first).status,200);assert.equal((await second).status,200);
  const controller=new AbortController();
  const held=[request('p-1-2',`?since=${cursor}&wait=10`,controller.signal),request('p-2-2',`?since=${cursor}&wait=10`,controller.signal)].map(p=>p.catch(error=>error.name));
  await new Promise(resolve=>setTimeout(resolve,30));
  assert.equal((await request('p-3-2',`?since=${cursor}&wait=0`)).status,200,'idle waits do not reserve read slots');
  controller.abort();
  assert.deepEqual(await Promise.all(held),['AbortError','AbortError']);
});
